Tracefoss 935 switch build tool of backend repo to maven
catenax-ng/tx-traceability-foss-backend pull request #24
Opened 2023-02-15 06:26 UTC by graflmsg

2023-02-15 11:10 UTC, mkanal submitted a review, later dismissed
There are still AC to fulfill. Please let us discuss how to achieve the ACs. Thx.

2023-02-16 21:39 UTC, ds-mwesener requested changes
Hi @graflmsg could you please review my comments. Thanks!

2023-02-16 21:39 UTC, ds-mwesener commented on .github/workflows/pull-request.yml
> +        run: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --batch-mode clean test
Currently the mvn test phase does not cover the unit tests of the projects because our unit tests does not match the standard location and naming convention.
For example: AssetFacadeSpec will never be executed.

Please make sure those tests will be executed here.

2023-02-16 21:39 UTC, ds-mwesener commented on .github/workflows/pull-request.yml
> +        run: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --batch-mode -DskipTests=true -DskipTests=true clean package sonar:sonar
Here the -DskipTests=true is doubled. Please remove one.

2023-02-16 21:39 UTC, ds-mwesener commented on config/dependency_check/suppressions.xml
> +		<cpe>cpe:/a:apache:struts:2.0.0</cpe>
Why we suppress this vulnerability? Could not find it within project:  mvn dependency:tree | grep "apache:struts"

2023-02-20 08:17 UTC, ds-mwesener commented
From my side we can merge pull request, once the conflicts have been resolved.

2023-02-20 08:42 UTC, ds-mwesener approved these changes

2023-02-22 07:55 UTC, merged