Adding the following possible version of the Spring Security Web
catenax-ng/tx-traceability-foss-backend pull request #66
Opened 2023-02-27 08:53 UTC by graflmsg

2023-02-27 11:15 UTC, dblankevia requested changes

2023-02-27 11:15 UTC, dblankevia commented on pom.xml
> +			<version>5.7.5</version>
We should use the latest bugfix version 5.7.7, if we have to manually upgrade the lib.

2023-02-28 06:23 UTC, ds-mwesener commented on pom.xml
> +			<version>5.7.5</version>
As far as I could see: We are currently using spring bom: 2.7.5. Which includes spring-security-web-5.7.4.

If we need to have a higher version we have to do it manually like done here.

https://docs.spring.io/spring-boot/docs/2.7.5/reference/html/dependency-versions.html#appendix.dependency-versions

2023-02-28 07:50 UTC, dblankevia commented on pom.xml
> +			<version>5.7.5</version>
We were already on Spring Boot 2.7.7 with the Gradle build. Please upgrade.

2023-02-28 08:53 UTC, dblankevia commented
We get the transitive dependency `org.springframework:spring-web:jar:5.3.24:compile`. We have to use 5.3.25, due to vulnerabilities in 5.3.24.

2023-02-28 09:04 UTC, dblankevia approved these changes

2023-02-28 09:08 UTC, merged